export const siteConfig = {
  name: 'Rising Generation (RIGO)',
  shortName: 'RIGO',
  description: 'Empowering Nigeria\'s next generation of leaders through education, entrepreneurship, career development and civic engagement.',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://risinggeneration.org',
  email: 'info@risinggeneration.org',
  phone: '+234 XXX XXX XXXX',
  whatsapp: 'https://wa.me/234XXXXXXXXXX',
  address: {
    street: 'Plot XX, XXXX Street',
    city: 'Abuja',
    state: 'FCT',
    country: 'Nigeria',
  },
  social: {
    instagram: 'https://instagram.com/risinggeneration_ng',
    twitter: 'https://twitter.com/raborigo',
    facebook: 'https://facebook.com/risinggeneration',
    linkedin: 'https://linkedin.com/company/rising-generation-ng',
  },
  initiatives: [
    {
      id: 'youngceo',
      title: 'YoungCEO Initiative',
      shortTitle: 'YoungCEO',
      tagline: 'Building Tomorrow\'s Business Leaders',
      description: 'Through our programs, we create, encourage and support young entrepreneurs by providing mentorship, training, and access to resources that help them build sustainable businesses. The YoungCEO initiative equips young Nigerians with the entrepreneurial mindset and practical skills needed to launch and grow their ventures.',
      features: [
        'Entrepreneurship training workshops',
        'Business mentorship programs',
        'Startup incubation support',
        'Networking events with industry leaders',
      ],
      color: '#1C8E9C',
      icon: '💼',
    },
    {
      id: 'rigo-careers',
      title: 'RIGO Careers',
      shortTitle: 'RIGO Careers',
      tagline: 'Connecting Youth to Opportunities',
      description: 'We help youths find jobs by providing skills necessary for employment, career guidance, and connecting them with employers who value young talent. RIGO Careers bridges the gap between education and employment, ensuring that young Nigerians are workforce-ready and can access meaningful career opportunities.',
      features: [
        'Career counseling and guidance',
        'Resume building workshops',
        'Job placement assistance',
        'Professional development training',
      ],
      color: '#145A61',
      icon: '🎯',
    },
    {
      id: 'unitednigeria',
      title: 'UnitedNigeria',
      shortTitle: 'UnitedNigeria',
      tagline: 'One Nation, One Vision',
      description: 'Promotes unity, political awareness and nation-building among Nigerian youth. The UnitedNigeria initiative fosters dialogue, civic engagement, and a shared vision for national development. We believe that an informed and united youth population is the foundation of a prosperous Nigeria.',
      features: [
        'Civic education programs',
        'Inter-ethnic dialogue forums',
        'Youth political awareness campaigns',
        'Nation-building conferences',
      ],
      color: '#1C8E9C',
      icon: '🇳🇬',
    },
    {
      id: 'rigo-learning',
      title: 'RIGO Learning',
      shortTitle: 'RIGO Learning',
      tagline: 'Education for Every Nigerian Youth',
      description: 'Promotes education, STEM and literacy development across communities. RIGO Learning provides educational resources, tutoring, and technology access to underserved communities, ensuring that every young Nigerian has the opportunity to learn, grow, and contribute to national development.',
      features: [
        'STEM education outreach',
        'Literacy development programs',
        'Digital skills training',
        'Educational resource distribution',
      ],
      color: '#145A61',
      icon: '📚',
    },
  ],
  nigerianStates: [
    'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue', 'Borno',
    'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'FCT', 'Gombe',
    'Imo', 'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara',
    'Lagos', 'Nasarawa', 'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo', 'Plateau',
    'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara',
  ],
}
